name: Mark and Maryna
favicon: null
layout_spectrum: 0.00623
typography_spectrum: 0.50267
author:
  name: ''
  email: ''
title: Memories from our wedding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
