name: Mark and Maryna
favicon: null
layout_spectrum: 0.9807173933368176
typography_spectrum: 0.4373431692365557
author:
  name: ''
  email: ''
title: Memories from our wedding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.46226366702467203
purpose: []
